In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv(r"C:\Users\HP\Downloads\hr_analytics.xls")

In [2]:
df

,Age,Gender,Department,MonthlyIncome,TotalWorkingYears,YearsAtCompany,JobSatisfaction,WorkLifeBalance,OverTime,Attrition
0,50,Female,HR,4753,14,8,2,1,Yes,No
1,36,Male,R&D,13123,3,7,3,4,No,No
2,29,Male,HR,19376,16,15,1,3,Yes,No
3,42,Male,HR,9588,19,14,2,4,No,Yes
4,40,Male,R&D,9304,18,8,2,3,No,Yes
...,...,...,...,...,...,...,...,...,...,...
995,34,Female,Sales,7986,2,5,4,3,Yes,Yes
996,51,Female,Sales,4481,26,12,4,2,Yes,No
997,44,Male,HR,6731,27,6,4,1,No,No
998,40,Female,Sales,19835,27,9,1,2,No,No
999,53,Female,HR,13758,15,1,2,4,No,No

In [5]:
df.head

<bound method NDFrame.head of      Age  Gender Department  MonthlyIncome  TotalWorkingYears  YearsAtCompany  \
0     50  Female         HR           4753                 14               8
1     36    Male        R&D          13123                  3               7
2     29    Male         HR          19376                 16              15
3     42    Male         HR           9588                 19              14
4     40    Male        R&D           9304                 18               8
..   ...     ...        ...            ...                ...             ...
995   34  Female      Sales           7986                  2               5
996   51  Female      Sales           4481                 26              12
997   44    Male         HR           6731                 27               6
998   40  Female      Sales          19835                 27               9
999   53  Female         HR          13758                 15               1

     JobSatisfaction  WorkLifeBalance OverTime Attrition
0                  2                1      Yes        No
1                  3                4       No        No
2                  1                3      Yes        No
3                  2                4       No       Yes
4                  2                3       No       Yes
..               ...              ...      ...       ...
995                4                3      Yes       Yes
996                4                2      Yes        No
997                4                1       No        No
998                1                2       No        No
999                2                4       No        No

[1000 rows x 10 columns]>

In [7]:
df.shape

(1000, 10)

In [13]:
df.dtypes

Age                   int64
Gender               object
Department           object
MonthlyIncome         int64
TotalWorkingYears     int64
YearsAtCompany        int64
JobSatisfaction       int64
WorkLifeBalance       int64
OverTime             object
Attrition            object
dtype: object

In [15]:
df.isnull().sum()

Age                  0
Gender               0
Department           0
MonthlyIncome        0
TotalWorkingYears    0
YearsAtCompany       0
JobSatisfaction      0
WorkLifeBalance      0
OverTime             0
Attrition            0
dtype: int64

In [23]:
df.duplicated().sum()

0

In [27]:
len(df)

1000

In [29]:
df['Department'].nunique()

3

In [31]:
df['Department'].unique()

array(['HR', 'R&D', 'Sales'], dtype=object)

In [33]:
df['Age'].mean()

40.947

In [39]:
df['Age'].min()

22

In [41]:
df['Age'].max()

59

In [47]:
print(round(df['MonthlyIncome'].mean(),2))

11496.43

In [49]:
df['MonthlyIncome'].min()

3024

In [51]:
df['MonthlyIncome'].max()

19998

In [55]:
df['Gender'].value_counts()

Gender
Male      504
Female    496
Name: count, dtype: int64

In [57]:
df['Department'].value_counts()

Department
HR       352
Sales    343
R&D      305
Name: count, dtype: int64

In [59]:
(df['TotalWorkingYears']>10).value_counts()

TotalWorkingYears
True     720
False    280
Name: count, dtype: int64

In [61]:
t=df['TotalWorkingYears']>10
print(t.sum())

720

In [65]:
t=df['YearsAtCompany']>5
print(t.sum())

752

In [69]:
dept_emp=df.groupby('Department')['MonthlyIncome'].mean()
dept_sal

Department
HR       11604.042614
R&D      11461.272131
Sales    11417.247813
Name: MonthlyIncome, dtype: float64

In [79]:
df[df['Attrition'] == 'Yes'].groupby('Department')['Attrition'].count()

Department
HR       70
R&D      74
Sales    59
Name: Attrition, dtype: int64

In [81]:
df.groupby('Department')['YearsAtCompany'].sum()

Department
HR       3649
R&D      3184
Sales    3440
Name: YearsAtCompany, dtype: int64

In [83]:
df.groupby('Department')['JobSatisfaction'].mean()

Department
HR       2.446023
R&D      2.465574
Sales    2.513120
Name: JobSatisfaction, dtype: float64

In [85]:
df.groupby('Gender')[['JobSatisfaction','WorkLifeBalance']].mean()

        JobSatisfaction  WorkLifeBalance
Gender
Female         2.512097         2.463710
Male           2.438492         2.462302