In [1]:
import pandas as pd
df=pd.read_csv("drug200.csv")

In [2]:
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    object
 2   BP           200 non-null    object
 3   Cholesterol  200 non-null    object
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

In [4]:
df.describe()

              Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [5]:
df.columns

Index(['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K', 'Drug'], dtype='object')

In [6]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [7]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Length: 200, dtype: bool

In [8]:
df.shape

(200, 6)

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df['Age'].value_counts()

Age
47    8
23    7
28    7
49    7
32    6
39    6
50    5
60    5
22    5
37    5
58    5
43    4
41    4
57    4
65    4
61    4
74    4
45    4
56    4
24    4
26    4
67    4
68    4
31    4
34    4
51    4
42    4
20    4
72    4
36    4
69    3
18    3
16    3
35    3
59    3
64    3
53    3
38    3
70    3
15    3
40    3
55    2
52    2
48    2
29    2
73    2
46    2
66    2
62    2
19    2
63    1
33    1
17    1
54    1
30    1
21    1
25    1
Name: count, dtype: int64

In [11]:
df['BP'].unique()

array(['HIGH', 'LOW', 'NORMAL'], dtype=object)

In [12]:
df['Cholesterol'].unique()

array(['HIGH', 'NORMAL'], dtype=object)

In [13]:
df['Drug'].unique()

array(['DrugY', 'drugC', 'drugX', 'drugA', 'drugB'], dtype=object)

In [17]:
df['Sex'].value_counts().unique()

array([104,  96])

In [18]:
df['Na_to_K'].unique()

array([25.355, 13.093, 10.114,  7.798, 18.043,  8.607, 16.275, 11.037,
       15.171, 19.368, 11.767, 19.199, 15.376, 20.942, 12.703, 15.516,
       11.455, 13.972,  7.298, 25.974, 19.128, 25.917, 30.568, 15.036,
       33.486, 18.809, 30.366,  9.381, 22.697, 17.951,  8.75 ,  9.567,
       11.014, 31.876, 14.133,  7.285,  9.445, 13.938,  9.709,  9.084,
       19.221, 14.239, 15.79 , 12.26 , 12.295,  8.107, 13.091, 10.291,
       31.686, 19.796, 19.416, 10.898, 27.183, 18.457, 10.189, 14.16 ,
       11.34 , 27.826, 10.091, 18.703, 29.875,  9.475, 20.693,  8.37 ,
       13.303, 27.05 , 12.856, 10.832, 24.658, 24.276, 13.967, 19.675,
       10.605, 22.905, 17.069, 20.909, 11.198, 19.161, 13.313, 10.84 ,
       13.934,  7.761,  9.712, 11.326, 10.067, 13.935, 13.597, 15.478,
       23.091, 17.211, 16.594, 15.156, 29.45 , 29.271, 15.015, 11.424,
       38.247, 25.395, 35.639, 16.725, 11.871, 12.854, 13.127,  8.966,
       28.294,  8.968, 11.953, 20.013,  9.677, 16.85 ,  7.49 ,  6.683,
        9.17 , 13.769,  9.281, 18.295,  9.514, 10.103, 10.292, 25.475,
       27.064, 17.206, 22.456, 16.753, 12.495, 25.969, 16.347,  7.845,
       33.542,  7.477, 20.489, 32.922, 13.598, 25.786, 21.036, 11.939,
       10.977, 12.894, 11.343, 10.065,  6.269, 25.741,  8.621, 15.436,
        9.664,  9.443, 12.006, 12.307,  7.34 ,  8.151,  8.7  , 11.009,
        7.261, 14.642, 16.724, 10.537, 11.227, 22.963, 10.444, 12.923,
       10.443,  9.945, 12.859, 28.632, 19.007, 26.645, 14.216, 23.003,
       11.262, 12.879, 10.017, 17.225, 18.739, 12.766, 18.348, 10.446,
       19.011, 15.969, 15.891, 22.818, 13.884, 11.686, 15.49 , 37.188,
       25.893,  9.849, 10.403, 34.997, 20.932, 18.991,  8.011, 16.31 ,
        6.769, 34.686, 11.567,  9.894, 14.02 , 11.349])

In [21]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Sex']=le.fit_transform(df['Sex'])

In [22]:
df

     Age  Sex      BP Cholesterol  Na_to_K   Drug
0      8    0    HIGH        HIGH   25.355  DrugY
1     30    1     LOW        HIGH   13.093  drugC
2     30    1     LOW        HIGH   10.114  drugC
3     12    0  NORMAL        HIGH    7.798  drugX
4     44    0     LOW        HIGH   18.043  DrugY
..   ...  ...     ...         ...      ...    ...
195   39    0     LOW        HIGH   11.567  drugC
196    1    1     LOW        HIGH   12.006  drugC
197   35    1  NORMAL        HIGH    9.894  drugX
198    8    1  NORMAL      NORMAL   14.020  drugX
199   24    0     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [23]:
df['BP']=le.fit_transform(df['BP'])

In [24]:
df

     Age  Sex  BP Cholesterol  Na_to_K   Drug
0      8    0   0        HIGH   25.355  DrugY
1     30    1   1        HIGH   13.093  drugC
2     30    1   1        HIGH   10.114  drugC
3     12    0   2        HIGH    7.798  drugX
4     44    0   1        HIGH   18.043  DrugY
..   ...  ...  ..         ...      ...    ...
195   39    0   1        HIGH   11.567  drugC
196    1    1   1        HIGH   12.006  drugC
197   35    1   2        HIGH    9.894  drugX
198    8    1   2      NORMAL   14.020  drugX
199   24    0   1      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [26]:
df['Drug']=le.fit_transform(df['Drug'])
df

     Age  Sex  BP Cholesterol  Na_to_K  Drug
0      8    0   0        HIGH   25.355     0
1     30    1   1        HIGH   13.093     3
2     30    1   1        HIGH   10.114     3
3     12    0   2        HIGH    7.798     4
4     44    0   1        HIGH   18.043     0
..   ...  ...  ..         ...      ...   ...
195   39    0   1        HIGH   11.567     3
196    1    1   1        HIGH   12.006     3
197   35    1   2        HIGH    9.894     4
198    8    1   2      NORMAL   14.020     4
199   24    0   1      NORMAL   11.349     4

[200 rows x 6 columns]

In [27]:
df['Cholesterol']=le.fit_transform(df['Cholesterol'])

In [28]:
df

     Age  Sex  BP  Cholesterol  Na_to_K  Drug
0      8    0   0            0   25.355     0
1     30    1   1            0   13.093     3
2     30    1   1            0   10.114     3
3     12    0   2            0    7.798     4
4     44    0   1            0   18.043     0
..   ...  ...  ..          ...      ...   ...
195   39    0   1            0   11.567     3
196    1    1   1            0   12.006     3
197   35    1   2            0    9.894     4
198    8    1   2            1   14.020     4
199   24    0   1            1   11.349     4

[200 rows x 6 columns]

In [33]:
x = df.drop("Drug", axis=1)

In [30]:
y=df['Drug']

In [31]:
from sklearn.model_selection import train_test_split

In [34]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [35]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
model=RandomForestClassifier(n_estimators=100,random_state=42)

In [37]:
model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [38]:
y_pred = model.predict(x_test)

In [39]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [40]:
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

1.0

In [41]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00         3
           3       1.00      1.00      1.00         5
           4       1.00      1.00      1.00        11

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40

In [42]:
print(confusion_matrix(y_test, y_pred))

[[15  0  0  0  0]
 [ 0  6  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0  5  0]
 [ 0  0  0  0 11]]